DROP DATABASE IF EXISTS `SGU_C_Sharf`;
CREATE DATABASE IF NOT EXISTS `SGU_C_Sharf`;
USE `SGU_C_Sharf`;
DROP TABLE IF EXISTS `ThanhVien`;
CREATE TABLE IF NOT EXISTS 'ThanhVien' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    HoTen NVARCHAR(255) NOT NULL,
    NgaySinh DATE NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    SoDienThoai NVARCHAR(10) NOT NULL,
    TrangThai ENUM('HOATDONG', 'DINHCHI', 'CAM') NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL,
    ThoiGianDangKy DATETIME NOT NULL DEFAULT NOW()
);
DROP TABLE IF EXISTS `CheckIn`;
CREATE TABLE IF NOT EXISTS 'CheckIn' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ThoiGianCheckIn DATETIME NOT NULL DEFAULT NOW()
);
DROP TABLE IF EXISTS `PhieuXuPhat`;
CREATE TABLE IF NOT EXISTS 'PhieuXuPhat' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TrangThai ENUM('CHUA_XU_LY', 'DA_XU_LY') NOT NULL,
    NgayViPham DATETIME NOT NULL DEFAULT NOW(),
    MoTa NVARCHAR(255) NOT NULL,
    ThoiHanXuPhat INT UNSIGNED,
    MucPhat INT UNSIGNED
);
DROP TABLE IF EXISTS `LoaiThietBi`;
CREATE TABLE IF NOT EXISTS 'LoaiThietBi' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenLoaiThietBi NVARCHAR(255) NOT NULL
);
DROP TABLE IF EXISTS `ThietBi`;
CREATE TABLE IF NOT EXISTS 'ThietBi' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenThietBi NVARCHAR(255) NOT NULL,
    IdLoaiThietBi INT UNSIGNED NOT NULL,
    FOREIGN KEY (IdLoaiThietBi) REFERENCES LoaiThietBi(Id)
);
DROP TABLE IF EXISTS `DauThietBi`;
CREATE TABLE IF NOT EXISTS 'DauThietBi' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TrangThai ENUM(
        'KHADUNG',
        'DATTRUOC',
        'DANGMUON',
        'THATLAC',
        'BAOTRI',
        'THANHLY',
        'DATHATLAC'
    ) NOT NULL,
    ThoiGianMua DATETIME NOT NULL,
    IdThietBi INT UNSIGNED NOT NULL,
    FOREIGN KEY (IdThietBi) REFERENCES ThietBi(Id)
);
DROP TABLE IF EXISTS `PhieuDatCho`;
CREATE TABLE IF NOT EXISTS 'PhieuDatCho' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IdThanhVien INT UNSIGNED NOT NULL,
    TrangThai ENUM('HUY', 'DANGCHO', 'DANGSUDUNG', 'DATRACHO') NOT NULL,
    ThoiGianDat DATETIME NOT NULL DEFAULT NOW(),
    ThoiGianLapPhieu DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (IdThanhVien) REFERENCES ThanhVien(Id)
);
DROP TABLE IF EXISTS `ChiTietPhieuDatCho`;
CREATE TABLE IF NOT EXISTS 'ChiTietPhieuDatCho' (
    IdPhieuDat INT UNSIGNED NOT NULL,
    IdDauThietBi INT UNSIGNED NOT NULL,
    PRIMARY KEY (IdPhieuDat, IdDauThietBi),
    FOREIGN KEY (IdPhieuDat) REFERENCES PhieuDatCho(Id),
    FOREIGN KEY (IdDauThietBi) REFERENCES DauThietBi(Id)
);
DROP TABLE IF EXISTS `PhieuMuon`;
CREATE TABLE IF NOT EXISTS 'PhieuMuon' (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TrangThai ENUM('HUY', 'DANGSUDUNG', 'DATRATHIETBI') NOT NULL,
    NgayTao DATETIME NOT NULL
);
DROP TABLE IF EXISTS `ChiTietPhieuMuon`;
CREATE TABLE IF NOT EXISTS 'ChiTietPhieuMuon' (
    IdPhieuMuon INT UNSIGNED NOT NULL,
    IdDauThietBi INT UNSIGNED NOT NULL,
    ThoiGianMuon DATETIME NOT NULL,
    ThoiGianTra DATETIME NOT NULL,
    TrangThai ENUM('DANGMUON', 'DATRATHIETBI', 'DATHATLAC') NOT NULL,
    PRIMARY KEY (IdPhieuMuon, IdDauThietBi),
    FOREIGN KEY (IdPhieuMuon) REFERENCES PhieuMuon(Id),
    FOREIGN KEY (IdDauThietBi) REFERENCES DauThietBi(Id)
);